name: newsplus
description: A new Flutter project.

publish_to: "none" 
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  shimmer: ^2.0.0
  provider: ^6.0.2
  localstore: ^1.2.1
  url_launcher: ^6.0.20
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.1
  webview_flutter: ^4.0.7
  cached_network_image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.0

flutter_launcher_icons:
  android: "launcher_icon"
  min_sdk_android: 20
  image_path: assets/images/logo.png
  adaptive_icon_foreground: assets/images/logo.png
  adaptive_icon_background: "#000000"

flutter_native_splash:
  ios: false
  web: false
  color: "#000000"
  image: assets/images/logo.png
  android12:
    color: "#000000"
    branding: assets/images/logo.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/empty.png
    - assets/images/illustration.png
    - assets/images/error.png
    - assets/images/gone.png

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic